set( GSL_SOURCE_DIR "${CMAKE_SOURCE_DIR}/gsl-1.0")
set( GSL_SOURCES 
  ${GSL_SOURCE_DIR}/dht/dht.c
  ${GSL_SOURCE_DIR}/ode-initval/control.c
  ${GSL_SOURCE_DIR}/ode-initval/cstd.c
  ${GSL_SOURCE_DIR}/ode-initval/evolve.c
  ${GSL_SOURCE_DIR}/ode-initval/step.c
  ${GSL_SOURCE_DIR}/ode-initval/rk2.c
  ${GSL_SOURCE_DIR}/ode-initval/rk2imp.c
  ${GSL_SOURCE_DIR}/ode-initval/rk4.c
  ${GSL_SOURCE_DIR}/ode-initval/rk4imp.c
  ${GSL_SOURCE_DIR}/ode-initval/rkf45.c
  ${GSL_SOURCE_DIR}/ode-initval/rk8pd.c
  ${GSL_SOURCE_DIR}/ode-initval/rkck.c
  ${GSL_SOURCE_DIR}/ode-initval/bsimp.c
  ${GSL_SOURCE_DIR}/ode-initval/gear1.c
  ${GSL_SOURCE_DIR}/ode-initval/gear2.c
  ${GSL_SOURCE_DIR}/permutation/init.c
  ${GSL_SOURCE_DIR}/permutation/file.c
  ${GSL_SOURCE_DIR}/permutation/permutation.c
  ${GSL_SOURCE_DIR}/permutation/permute.c
  ${GSL_SOURCE_DIR}/sum/levin_u.c
  ${GSL_SOURCE_DIR}/sum/levin_utrunc.c
  ${GSL_SOURCE_DIR}/sum/work_u.c
  ${GSL_SOURCE_DIR}/sum/work_utrunc.c
  ${GSL_SOURCE_DIR}/vector/init.c
  ${GSL_SOURCE_DIR}/vector/file.c
  ${GSL_SOURCE_DIR}/vector/vector.c
  ${GSL_SOURCE_DIR}/vector/copy.c
  ${GSL_SOURCE_DIR}/vector/swap.c
  ${GSL_SOURCE_DIR}/vector/prop.c
  ${GSL_SOURCE_DIR}/vector/minmax.c
  ${GSL_SOURCE_DIR}/vector/oper.c
  ${GSL_SOURCE_DIR}/vector/reim.c
  ${GSL_SOURCE_DIR}/vector/subvector.c
  ${GSL_SOURCE_DIR}/vector/view.c
  ${GSL_SOURCE_DIR}/vector/view.h
  ${GSL_SOURCE_DIR}/qrng/qrng.c
  ${GSL_SOURCE_DIR}/qrng/niederreiter-2.c
  ${GSL_SOURCE_DIR}/qrng/sobol.c
  ${GSL_SOURCE_DIR}/multifit/multilinear.c
  ${GSL_SOURCE_DIR}/multifit/work.c
  ${GSL_SOURCE_DIR}/multifit/lmder.c
  ${GSL_SOURCE_DIR}/multifit/fsolver.c
  ${GSL_SOURCE_DIR}/multifit/fdfsolver.c
  ${GSL_SOURCE_DIR}/multifit/convergence.c
  ${GSL_SOURCE_DIR}/multifit/gradient.c
  ${GSL_SOURCE_DIR}/multifit/covar.c
  ${GSL_SOURCE_DIR}/cblas/sasum.c
  ${GSL_SOURCE_DIR}/cblas/saxpy.c
  ${GSL_SOURCE_DIR}/cblas/scasum.c
  ${GSL_SOURCE_DIR}/cblas/scnrm2.c
  ${GSL_SOURCE_DIR}/cblas/scopy.c
  ${GSL_SOURCE_DIR}/cblas/sdot.c
  ${GSL_SOURCE_DIR}/cblas/sdsdot.c
  ${GSL_SOURCE_DIR}/cblas/sgbmv.c
  ${GSL_SOURCE_DIR}/cblas/sgemm.c
  ${GSL_SOURCE_DIR}/cblas/sgemv.c
  ${GSL_SOURCE_DIR}/cblas/sger.c
  ${GSL_SOURCE_DIR}/cblas/snrm2.c
  ${GSL_SOURCE_DIR}/cblas/srot.c
  ${GSL_SOURCE_DIR}/cblas/srotg.c
  ${GSL_SOURCE_DIR}/cblas/srotm.c
  ${GSL_SOURCE_DIR}/cblas/srotmg.c
  ${GSL_SOURCE_DIR}/cblas/ssbmv.c
  ${GSL_SOURCE_DIR}/cblas/sscal.c
  ${GSL_SOURCE_DIR}/cblas/sspmv.c
  ${GSL_SOURCE_DIR}/cblas/sspr.c
  ${GSL_SOURCE_DIR}/cblas/sspr2.c
  ${GSL_SOURCE_DIR}/cblas/sswap.c
  ${GSL_SOURCE_DIR}/cblas/ssymm.c
  ${GSL_SOURCE_DIR}/cblas/ssymv.c
  ${GSL_SOURCE_DIR}/cblas/ssyr.c
  ${GSL_SOURCE_DIR}/cblas/ssyr2.c
  ${GSL_SOURCE_DIR}/cblas/ssyr2k.c
  ${GSL_SOURCE_DIR}/cblas/ssyrk.c
  ${GSL_SOURCE_DIR}/cblas/stbmv.c
  ${GSL_SOURCE_DIR}/cblas/stbsv.c
  ${GSL_SOURCE_DIR}/cblas/stpmv.c
  ${GSL_SOURCE_DIR}/cblas/stpsv.c
  ${GSL_SOURCE_DIR}/cblas/strmm.c
  ${GSL_SOURCE_DIR}/cblas/strmv.c
  ${GSL_SOURCE_DIR}/cblas/strsm.c
  ${GSL_SOURCE_DIR}/cblas/strsv.c
  ${GSL_SOURCE_DIR}/cblas/dasum.c
  ${GSL_SOURCE_DIR}/cblas/daxpy.c
  ${GSL_SOURCE_DIR}/cblas/dcopy.c
  ${GSL_SOURCE_DIR}/cblas/ddot.c
  ${GSL_SOURCE_DIR}/cblas/dgbmv.c
  ${GSL_SOURCE_DIR}/cblas/dgemm.c
  ${GSL_SOURCE_DIR}/cblas/dgemv.c
  ${GSL_SOURCE_DIR}/cblas/dger.c
  ${GSL_SOURCE_DIR}/cblas/dnrm2.c
  ${GSL_SOURCE_DIR}/cblas/drot.c
  ${GSL_SOURCE_DIR}/cblas/drotg.c
  ${GSL_SOURCE_DIR}/cblas/drotm.c
  ${GSL_SOURCE_DIR}/cblas/drotmg.c
  ${GSL_SOURCE_DIR}/cblas/dsbmv.c
  ${GSL_SOURCE_DIR}/cblas/dscal.c
  ${GSL_SOURCE_DIR}/cblas/dsdot.c
  ${GSL_SOURCE_DIR}/cblas/dspmv.c
  ${GSL_SOURCE_DIR}/cblas/dspr.c
  ${GSL_SOURCE_DIR}/cblas/dspr2.c
  ${GSL_SOURCE_DIR}/cblas/dswap.c
  ${GSL_SOURCE_DIR}/cblas/dsymm.c
  ${GSL_SOURCE_DIR}/cblas/dsymv.c
  ${GSL_SOURCE_DIR}/cblas/dsyr.c
  ${GSL_SOURCE_DIR}/cblas/dsyr2.c
  ${GSL_SOURCE_DIR}/cblas/dsyr2k.c
  ${GSL_SOURCE_DIR}/cblas/dsyrk.c
  ${GSL_SOURCE_DIR}/cblas/dtbmv.c
  ${GSL_SOURCE_DIR}/cblas/dtbsv.c
  ${GSL_SOURCE_DIR}/cblas/dtpmv.c
  ${GSL_SOURCE_DIR}/cblas/dtpsv.c
  ${GSL_SOURCE_DIR}/cblas/dtrmm.c
  ${GSL_SOURCE_DIR}/cblas/dtrmv.c
  ${GSL_SOURCE_DIR}/cblas/dtrsm.c
  ${GSL_SOURCE_DIR}/cblas/dtrsv.c
  ${GSL_SOURCE_DIR}/cblas/dzasum.c
  ${GSL_SOURCE_DIR}/cblas/dznrm2.c
  ${GSL_SOURCE_DIR}/cblas/caxpy.c
  ${GSL_SOURCE_DIR}/cblas/ccopy.c
  ${GSL_SOURCE_DIR}/cblas/cdotc_sub.c
  ${GSL_SOURCE_DIR}/cblas/cdotu_sub.c
  ${GSL_SOURCE_DIR}/cblas/cgbmv.c
  ${GSL_SOURCE_DIR}/cblas/cgemm.c
  ${GSL_SOURCE_DIR}/cblas/cgemv.c
  ${GSL_SOURCE_DIR}/cblas/cgerc.c
  ${GSL_SOURCE_DIR}/cblas/cgeru.c
  ${GSL_SOURCE_DIR}/cblas/chbmv.c
  ${GSL_SOURCE_DIR}/cblas/chemm.c
  ${GSL_SOURCE_DIR}/cblas/chemv.c
  ${GSL_SOURCE_DIR}/cblas/cher.c
  ${GSL_SOURCE_DIR}/cblas/cher2.c
  ${GSL_SOURCE_DIR}/cblas/cher2k.c
  ${GSL_SOURCE_DIR}/cblas/cherk.c
  ${GSL_SOURCE_DIR}/cblas/chpmv.c
  ${GSL_SOURCE_DIR}/cblas/chpr.c
  ${GSL_SOURCE_DIR}/cblas/chpr2.c
  ${GSL_SOURCE_DIR}/cblas/cscal.c
  ${GSL_SOURCE_DIR}/cblas/csscal.c
  ${GSL_SOURCE_DIR}/cblas/cswap.c
  ${GSL_SOURCE_DIR}/cblas/csymm.c
  ${GSL_SOURCE_DIR}/cblas/csyr2k.c
  ${GSL_SOURCE_DIR}/cblas/csyrk.c
  ${GSL_SOURCE_DIR}/cblas/ctbmv.c
  ${GSL_SOURCE_DIR}/cblas/ctbsv.c
  ${GSL_SOURCE_DIR}/cblas/ctpmv.c
  ${GSL_SOURCE_DIR}/cblas/ctpsv.c
  ${GSL_SOURCE_DIR}/cblas/ctrmm.c
  ${GSL_SOURCE_DIR}/cblas/ctrmv.c
  ${GSL_SOURCE_DIR}/cblas/ctrsm.c
  ${GSL_SOURCE_DIR}/cblas/ctrsv.c
  ${GSL_SOURCE_DIR}/cblas/zaxpy.c
  ${GSL_SOURCE_DIR}/cblas/zcopy.c
  ${GSL_SOURCE_DIR}/cblas/zdotc_sub.c
  ${GSL_SOURCE_DIR}/cblas/zdotu_sub.c
  ${GSL_SOURCE_DIR}/cblas/zdscal.c
  ${GSL_SOURCE_DIR}/cblas/zgbmv.c
  ${GSL_SOURCE_DIR}/cblas/zgemm.c
  ${GSL_SOURCE_DIR}/cblas/zgemv.c
  ${GSL_SOURCE_DIR}/cblas/zgerc.c
  ${GSL_SOURCE_DIR}/cblas/zgeru.c
  ${GSL_SOURCE_DIR}/cblas/zhbmv.c
  ${GSL_SOURCE_DIR}/cblas/zhemm.c
  ${GSL_SOURCE_DIR}/cblas/zhemv.c
  ${GSL_SOURCE_DIR}/cblas/zher.c
  ${GSL_SOURCE_DIR}/cblas/zher2.c
  ${GSL_SOURCE_DIR}/cblas/zher2k.c
  ${GSL_SOURCE_DIR}/cblas/zherk.c
  ${GSL_SOURCE_DIR}/cblas/zhpmv.c
  ${GSL_SOURCE_DIR}/cblas/zhpr.c
  ${GSL_SOURCE_DIR}/cblas/zhpr2.c
  ${GSL_SOURCE_DIR}/cblas/zscal.c
  ${GSL_SOURCE_DIR}/cblas/zswap.c
  ${GSL_SOURCE_DIR}/cblas/zsymm.c
  ${GSL_SOURCE_DIR}/cblas/zsyr2k.c
  ${GSL_SOURCE_DIR}/cblas/zsyrk.c
  ${GSL_SOURCE_DIR}/cblas/ztbmv.c
  ${GSL_SOURCE_DIR}/cblas/ztbsv.c
  ${GSL_SOURCE_DIR}/cblas/ztpmv.c
  ${GSL_SOURCE_DIR}/cblas/ztpsv.c
  ${GSL_SOURCE_DIR}/cblas/ztrmm.c
  ${GSL_SOURCE_DIR}/cblas/ztrmv.c
  ${GSL_SOURCE_DIR}/cblas/ztrsm.c
  ${GSL_SOURCE_DIR}/cblas/ztrsv.c
  ${GSL_SOURCE_DIR}/cblas/icamax.c
  ${GSL_SOURCE_DIR}/cblas/idamax.c
  ${GSL_SOURCE_DIR}/cblas/isamax.c
  ${GSL_SOURCE_DIR}/cblas/izamax.c
  ${GSL_SOURCE_DIR}/cblas/xerbla.c
  ${GSL_SOURCE_DIR}/block/init.c
  ${GSL_SOURCE_DIR}/block/file.c
  ${GSL_SOURCE_DIR}/block/block.c
  ${GSL_SOURCE_DIR}/diff/diff.c
  ${GSL_SOURCE_DIR}/integration/qk15.c
  ${GSL_SOURCE_DIR}/integration/qk21.c
  ${GSL_SOURCE_DIR}/integration/qk31.c
  ${GSL_SOURCE_DIR}/integration/qk41.c
  ${GSL_SOURCE_DIR}/integration/qk51.c
  ${GSL_SOURCE_DIR}/integration/qk61.c
  ${GSL_SOURCE_DIR}/integration/qk.c
  ${GSL_SOURCE_DIR}/integration/qng.c
  ${GSL_SOURCE_DIR}/integration/qng.h
  ${GSL_SOURCE_DIR}/integration/qag.c
  ${GSL_SOURCE_DIR}/integration/qags.c
  ${GSL_SOURCE_DIR}/integration/qagp.c
  ${GSL_SOURCE_DIR}/integration/workspace.c
  ${GSL_SOURCE_DIR}/integration/qcheb.c
  ${GSL_SOURCE_DIR}/integration/qawc.c
  ${GSL_SOURCE_DIR}/integration/qmomo.c
  ${GSL_SOURCE_DIR}/integration/qaws.c
  ${GSL_SOURCE_DIR}/integration/qmomof.c
  ${GSL_SOURCE_DIR}/integration/qawo.c
  ${GSL_SOURCE_DIR}/integration/qawf.c
  ${GSL_SOURCE_DIR}/fit/linear.c
  ${GSL_SOURCE_DIR}/ieee-utils/print.c
  ${GSL_SOURCE_DIR}/ieee-utils/make_rep.c
  ${GSL_SOURCE_DIR}/ieee-utils/gsl_ieee_utils.h
  ${GSL_SOURCE_DIR}/ieee-utils/env.c
  ${GSL_SOURCE_DIR}/ieee-utils/fp.c
  ${GSL_SOURCE_DIR}/ieee-utils/read.c
  ${GSL_SOURCE_DIR}/eigen/jacobi.c
  ${GSL_SOURCE_DIR}/eigen/symm.c
  ${GSL_SOURCE_DIR}/eigen/symmv.c
  ${GSL_SOURCE_DIR}/eigen/herm.c
  ${GSL_SOURCE_DIR}/eigen/hermv.c
  ${GSL_SOURCE_DIR}/eigen/sort.c
  ${GSL_SOURCE_DIR}/statistics/mean.c
  ${GSL_SOURCE_DIR}/statistics/variance.c
  ${GSL_SOURCE_DIR}/statistics/absdev.c
  ${GSL_SOURCE_DIR}/statistics/skew.c
  ${GSL_SOURCE_DIR}/statistics/kurtosis.c
  ${GSL_SOURCE_DIR}/statistics/lag1.c
  ${GSL_SOURCE_DIR}/statistics/p_variance.c
  ${GSL_SOURCE_DIR}/statistics/minmax.c
  ${GSL_SOURCE_DIR}/statistics/ttest.c
  ${GSL_SOURCE_DIR}/statistics/median.c
  ${GSL_SOURCE_DIR}/statistics/covariance.c
  ${GSL_SOURCE_DIR}/statistics/quantiles.c
  ${GSL_SOURCE_DIR}/statistics/wmean.c
  ${GSL_SOURCE_DIR}/statistics/wvariance.c
  ${GSL_SOURCE_DIR}/statistics/wabsdev.c
  ${GSL_SOURCE_DIR}/statistics/wskew.c
  ${GSL_SOURCE_DIR}/statistics/wkurtosis.c
  ${GSL_SOURCE_DIR}/roots/bisection.c
  ${GSL_SOURCE_DIR}/roots/brent.c
  ${GSL_SOURCE_DIR}/roots/falsepos.c
  ${GSL_SOURCE_DIR}/roots/newton.c
  ${GSL_SOURCE_DIR}/roots/secant.c
  ${GSL_SOURCE_DIR}/roots/steffenson.c
  ${GSL_SOURCE_DIR}/roots/convergence.c
  ${GSL_SOURCE_DIR}/roots/fsolver.c
  ${GSL_SOURCE_DIR}/roots/fdfsolver.c
  ${GSL_SOURCE_DIR}/linalg/multiply.c
  ${GSL_SOURCE_DIR}/linalg/tridiag.c
  ${GSL_SOURCE_DIR}/linalg/tridiag.h
  ${GSL_SOURCE_DIR}/linalg/lu.c
  ${GSL_SOURCE_DIR}/linalg/luc.c
  ${GSL_SOURCE_DIR}/linalg/hh.c
  ${GSL_SOURCE_DIR}/linalg/qr.c
  ${GSL_SOURCE_DIR}/linalg/qrpt.c
  ${GSL_SOURCE_DIR}/linalg/svd.c
  ${GSL_SOURCE_DIR}/linalg/householder.c
  ${GSL_SOURCE_DIR}/linalg/householdercomplex.c
  ${GSL_SOURCE_DIR}/linalg/cholesky.c
  ${GSL_SOURCE_DIR}/linalg/symmtd.c
  ${GSL_SOURCE_DIR}/linalg/hermtd.c
  ${GSL_SOURCE_DIR}/linalg/bidiag.c
  ${GSL_SOURCE_DIR}/linalg/balance.c
  ${GSL_SOURCE_DIR}/min/fsolver.c
  ${GSL_SOURCE_DIR}/min/golden.c
  ${GSL_SOURCE_DIR}/min/brent.c
  ${GSL_SOURCE_DIR}/min/convergence.c
  ${GSL_SOURCE_DIR}/min/bracketing.c
  ${GSL_SOURCE_DIR}/utils/system.h
  ${GSL_SOURCE_DIR}/utils/placeholder.c
  ${GSL_SOURCE_DIR}/rng/rng.c
  ${GSL_SOURCE_DIR}/rng/types.c
  ${GSL_SOURCE_DIR}/rng/default.c
  ${GSL_SOURCE_DIR}/rng/cmrg.c
  ${GSL_SOURCE_DIR}/rng/gfsr4.c
  ${GSL_SOURCE_DIR}/rng/slatec.c
  ${GSL_SOURCE_DIR}/rng/minstd.c
  ${GSL_SOURCE_DIR}/rng/mrg.c
  ${GSL_SOURCE_DIR}/rng/mt.c
  ${GSL_SOURCE_DIR}/rng/r250.c
  ${GSL_SOURCE_DIR}/rng/ran0.c
  ${GSL_SOURCE_DIR}/rng/ran1.c
  ${GSL_SOURCE_DIR}/rng/ran2.c
  ${GSL_SOURCE_DIR}/rng/ran3.c
  ${GSL_SOURCE_DIR}/rng/rand.c
  ${GSL_SOURCE_DIR}/rng/random.c
  ${GSL_SOURCE_DIR}/rng/rand48.c
  ${GSL_SOURCE_DIR}/rng/randu.c
  ${GSL_SOURCE_DIR}/rng/ranf.c
  ${GSL_SOURCE_DIR}/rng/ranlux.c
  ${GSL_SOURCE_DIR}/rng/ranlxs.c
  ${GSL_SOURCE_DIR}/rng/ranlxd.c
  ${GSL_SOURCE_DIR}/rng/ranmar.c
  ${GSL_SOURCE_DIR}/rng/taus.c
  ${GSL_SOURCE_DIR}/rng/transputer.c
  ${GSL_SOURCE_DIR}/rng/tt.c
  ${GSL_SOURCE_DIR}/rng/uni.c
  ${GSL_SOURCE_DIR}/rng/uni32.c
  ${GSL_SOURCE_DIR}/rng/vax.c
  ${GSL_SOURCE_DIR}/rng/zuf.c
  ${GSL_SOURCE_DIR}/ntuple/ntuple.c
  ${GSL_SOURCE_DIR}/interpolation/accel.c
  ${GSL_SOURCE_DIR}/interpolation/akima.c
  ${GSL_SOURCE_DIR}/interpolation/bsearch.c
  ${GSL_SOURCE_DIR}/interpolation/cspline.c
  ${GSL_SOURCE_DIR}/interpolation/interp.c
  ${GSL_SOURCE_DIR}/interpolation/linear.c
  ${GSL_SOURCE_DIR}/interpolation/integ_eval.h
  ${GSL_SOURCE_DIR}/interpolation/spline.c
  ${GSL_SOURCE_DIR}/monte/miser.c
  ${GSL_SOURCE_DIR}/monte/plain.c
  ${GSL_SOURCE_DIR}/monte/gsl_monte_vegas.h
  ${GSL_SOURCE_DIR}/monte/gsl_monte_miser.h
  ${GSL_SOURCE_DIR}/monte/gsl_monte_plain.h
  ${GSL_SOURCE_DIR}/monte/gsl_monte.h
  ${GSL_SOURCE_DIR}/monte/vegas.c
  ${GSL_SOURCE_DIR}/poly/eval.c
  ${GSL_SOURCE_DIR}/poly/solve_quadratic.c
  ${GSL_SOURCE_DIR}/poly/solve_cubic.c
  ${GSL_SOURCE_DIR}/poly/zsolve_quadratic.c
  ${GSL_SOURCE_DIR}/poly/zsolve_cubic.c
  ${GSL_SOURCE_DIR}/poly/zsolve.c
  ${GSL_SOURCE_DIR}/poly/zsolve_init.c
  ${GSL_SOURCE_DIR}/blas/blas.c
  ${GSL_SOURCE_DIR}/err/error.c
  ${GSL_SOURCE_DIR}/err/stream.c
  ${GSL_SOURCE_DIR}/err/message.c
  ${GSL_SOURCE_DIR}/err/strerror.c
  ${GSL_SOURCE_DIR}/err/warn.c
  ${GSL_SOURCE_DIR}/cheb/deriv.c
  ${GSL_SOURCE_DIR}/cheb/eval.c
  ${GSL_SOURCE_DIR}/cheb/init.c
  ${GSL_SOURCE_DIR}/cheb/integ.c
  ${GSL_SOURCE_DIR}/siman/siman.c
  ${GSL_SOURCE_DIR}/complex/math.c
  ${GSL_SOURCE_DIR}/matrix/init.c
  ${GSL_SOURCE_DIR}/matrix/matrix.c
  ${GSL_SOURCE_DIR}/matrix/file.c
  ${GSL_SOURCE_DIR}/matrix/rowcol.c
  ${GSL_SOURCE_DIR}/matrix/swap.c
  ${GSL_SOURCE_DIR}/matrix/copy.c
  ${GSL_SOURCE_DIR}/matrix/minmax.c
  ${GSL_SOURCE_DIR}/matrix/prop.c
  ${GSL_SOURCE_DIR}/matrix/oper.c
  ${GSL_SOURCE_DIR}/matrix/getset.c
  ${GSL_SOURCE_DIR}/matrix/view.c
  ${GSL_SOURCE_DIR}/matrix/submatrix.c
  ${GSL_SOURCE_DIR}/matrix/view.h
  ${GSL_SOURCE_DIR}/fft/dft.c
  ${GSL_SOURCE_DIR}/fft/fft.c
  ${GSL_SOURCE_DIR}/sort/sort.c
  ${GSL_SOURCE_DIR}/sort/sortind.c
  ${GSL_SOURCE_DIR}/sort/sortvec.c
  ${GSL_SOURCE_DIR}/sort/sortvecind.c
  ${GSL_SOURCE_DIR}/sort/subset.c
  ${GSL_SOURCE_DIR}/sort/subsetind.c
  ${GSL_SOURCE_DIR}/sys/minmax.c
  ${GSL_SOURCE_DIR}/sys/prec.c
  ${GSL_SOURCE_DIR}/sys/hypot.c
  ${GSL_SOURCE_DIR}/sys/log1p.c
  ${GSL_SOURCE_DIR}/sys/expm1.c
  ${GSL_SOURCE_DIR}/sys/coerce.c
  ${GSL_SOURCE_DIR}/sys/invhyp.c
  ${GSL_SOURCE_DIR}/sys/pow_int.c
  ${GSL_SOURCE_DIR}/sys/infnan.c
  ${GSL_SOURCE_DIR}/sys/fdiv.c
  ${GSL_SOURCE_DIR}/specfunc/airy.c
  ${GSL_SOURCE_DIR}/specfunc/airy_der.c
  ${GSL_SOURCE_DIR}/specfunc/airy_zero.c
  ${GSL_SOURCE_DIR}/specfunc/atanint.c
  ${GSL_SOURCE_DIR}/specfunc/bessel.c
  ${GSL_SOURCE_DIR}/specfunc/bessel.h
  ${GSL_SOURCE_DIR}/specfunc/bessel_I0.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_I1.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_In.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_Inu.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_J0.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_J1.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_Jn.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_Jnu.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_K0.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_K1.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_Kn.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_Knu.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_Y0.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_Y1.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_Yn.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_Ynu.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_amp_phase.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_amp_phase.h
  ${GSL_SOURCE_DIR}/specfunc/bessel_i.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_j.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_k.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_olver.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_temme.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_y.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_zero.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_sequence.c
  ${GSL_SOURCE_DIR}/specfunc/beta.c
  ${GSL_SOURCE_DIR}/specfunc/beta_inc.c
  ${GSL_SOURCE_DIR}/specfunc/clausen.c
  ${GSL_SOURCE_DIR}/specfunc/coulomb.c
  ${GSL_SOURCE_DIR}/specfunc/coupling.c
  ${GSL_SOURCE_DIR}/specfunc/coulomb_bound.c
  ${GSL_SOURCE_DIR}/specfunc/dawson.c
  ${GSL_SOURCE_DIR}/specfunc/debye.c
  ${GSL_SOURCE_DIR}/specfunc/dilog.c
  ${GSL_SOURCE_DIR}/specfunc/elementary.c
  ${GSL_SOURCE_DIR}/specfunc/ellint.c
  ${GSL_SOURCE_DIR}/specfunc/elljac.c
  ${GSL_SOURCE_DIR}/specfunc/erfc.c
  ${GSL_SOURCE_DIR}/specfunc/exp.c
  ${GSL_SOURCE_DIR}/specfunc/expint.c
  ${GSL_SOURCE_DIR}/specfunc/expint3.c
  ${GSL_SOURCE_DIR}/specfunc/fermi_dirac.c
  ${GSL_SOURCE_DIR}/specfunc/gegenbauer.c
  ${GSL_SOURCE_DIR}/specfunc/gamma.c
  ${GSL_SOURCE_DIR}/specfunc/gamma_inc.c
  ${GSL_SOURCE_DIR}/specfunc/hyperg_0F1.c
  ${GSL_SOURCE_DIR}/specfunc/hyperg_2F0.c
  ${GSL_SOURCE_DIR}/specfunc/hyperg_1F1.c
  ${GSL_SOURCE_DIR}/specfunc/hyperg_2F1.c
  ${GSL_SOURCE_DIR}/specfunc/hyperg_U.c
  ${GSL_SOURCE_DIR}/specfunc/hyperg.c
  ${GSL_SOURCE_DIR}/specfunc/laguerre.c
  ${GSL_SOURCE_DIR}/specfunc/lambert.c
  ${GSL_SOURCE_DIR}/specfunc/legendre_H3d.c
  ${GSL_SOURCE_DIR}/specfunc/legendre_Qn.c
  ${GSL_SOURCE_DIR}/specfunc/legendre_con.c
  ${GSL_SOURCE_DIR}/specfunc/legendre_poly.c
  ${GSL_SOURCE_DIR}/specfunc/log.c
  ${GSL_SOURCE_DIR}/specfunc/poch.c
  ${GSL_SOURCE_DIR}/specfunc/pow_int.c
  ${GSL_SOURCE_DIR}/specfunc/psi.c
  ${GSL_SOURCE_DIR}/specfunc/recurse.h
  ${GSL_SOURCE_DIR}/specfunc/result.c
  ${GSL_SOURCE_DIR}/specfunc/shint.c
  ${GSL_SOURCE_DIR}/specfunc/sinint.c
  ${GSL_SOURCE_DIR}/specfunc/synchrotron.c
  ${GSL_SOURCE_DIR}/specfunc/transport.c
  ${GSL_SOURCE_DIR}/specfunc/trig.c
  ${GSL_SOURCE_DIR}/specfunc/zeta.c
  ${GSL_SOURCE_DIR}/multimin/fdfminimizer.c
  ${GSL_SOURCE_DIR}/multimin/steepest_descent.c
  ${GSL_SOURCE_DIR}/multimin/conjugate_fr.c
  ${GSL_SOURCE_DIR}/multimin/conjugate_pr.c
  ${GSL_SOURCE_DIR}/multimin/convergence.c
  ${GSL_SOURCE_DIR}/multimin/diff.c
  ${GSL_SOURCE_DIR}/multimin/vector_bfgs.c
  ${GSL_SOURCE_DIR}/histogram/add.c
  ${GSL_SOURCE_DIR}/histogram/get.c
  ${GSL_SOURCE_DIR}/histogram/init.c
  ${GSL_SOURCE_DIR}/histogram/params.c
  ${GSL_SOURCE_DIR}/histogram/reset.c
  ${GSL_SOURCE_DIR}/histogram/file.c
  ${GSL_SOURCE_DIR}/histogram/pdf.c
  ${GSL_SOURCE_DIR}/histogram/gsl_histogram.h
  ${GSL_SOURCE_DIR}/histogram/add2d.c
  ${GSL_SOURCE_DIR}/histogram/get2d.c
  ${GSL_SOURCE_DIR}/histogram/init2d.c
  ${GSL_SOURCE_DIR}/histogram/params2d.c
  ${GSL_SOURCE_DIR}/histogram/reset2d.c
  ${GSL_SOURCE_DIR}/histogram/file2d.c
  ${GSL_SOURCE_DIR}/histogram/pdf2d.c
  ${GSL_SOURCE_DIR}/histogram/gsl_histogram2d.h
  ${GSL_SOURCE_DIR}/histogram/calloc_range.c
  ${GSL_SOURCE_DIR}/histogram/calloc_range2d.c
  ${GSL_SOURCE_DIR}/histogram/copy.c
  ${GSL_SOURCE_DIR}/histogram/copy2d.c
  ${GSL_SOURCE_DIR}/histogram/maxval.c
  ${GSL_SOURCE_DIR}/histogram/maxval2d.c
  ${GSL_SOURCE_DIR}/histogram/oper.c
  ${GSL_SOURCE_DIR}/histogram/oper2d.c
  ${GSL_SOURCE_DIR}/histogram/stat.c
  ${GSL_SOURCE_DIR}/test/results.c
  ${GSL_SOURCE_DIR}/multiroots/fdjac.c
  ${GSL_SOURCE_DIR}/multiroots/fsolver.c
  ${GSL_SOURCE_DIR}/multiroots/fdfsolver.c
  ${GSL_SOURCE_DIR}/multiroots/convergence.c
  ${GSL_SOURCE_DIR}/multiroots/newton.c
  ${GSL_SOURCE_DIR}/multiroots/gnewton.c
  ${GSL_SOURCE_DIR}/multiroots/dnewton.c
  ${GSL_SOURCE_DIR}/multiroots/broyden.c
  ${GSL_SOURCE_DIR}/multiroots/hybrid.c
  ${GSL_SOURCE_DIR}/multiroots/hybridj.c
  ${GSL_SOURCE_DIR}/randist/bernoulli.c
  ${GSL_SOURCE_DIR}/randist/beta.c
  ${GSL_SOURCE_DIR}/randist/bigauss.c
  ${GSL_SOURCE_DIR}/randist/binomial.c
  ${GSL_SOURCE_DIR}/randist/cauchy.c
  ${GSL_SOURCE_DIR}/randist/chisq.c
  ${GSL_SOURCE_DIR}/randist/discrete.c
  ${GSL_SOURCE_DIR}/randist/erlang.c
  ${GSL_SOURCE_DIR}/randist/exponential.c
  ${GSL_SOURCE_DIR}/randist/exppow.c
  ${GSL_SOURCE_DIR}/randist/fdist.c
  ${GSL_SOURCE_DIR}/randist/flat.c
  ${GSL_SOURCE_DIR}/randist/gamma.c
  ${GSL_SOURCE_DIR}/randist/gauss.c
  ${GSL_SOURCE_DIR}/randist/gausstail.c
  ${GSL_SOURCE_DIR}/randist/geometric.c
  ${GSL_SOURCE_DIR}/randist/gumbel.c
  ${GSL_SOURCE_DIR}/randist/hyperg.c
  ${GSL_SOURCE_DIR}/randist/laplace.c
  ${GSL_SOURCE_DIR}/randist/levy.c
  ${GSL_SOURCE_DIR}/randist/logarithmic.c
  ${GSL_SOURCE_DIR}/randist/logistic.c
  ${GSL_SOURCE_DIR}/randist/lognormal.c
  ${GSL_SOURCE_DIR}/randist/nbinomial.c
  ${GSL_SOURCE_DIR}/randist/pareto.c
  ${GSL_SOURCE_DIR}/randist/pascal.c
  ${GSL_SOURCE_DIR}/randist/poisson.c
  ${GSL_SOURCE_DIR}/randist/rayleigh.c
  ${GSL_SOURCE_DIR}/randist/shuffle.c
  ${GSL_SOURCE_DIR}/randist/sphere.c
  ${GSL_SOURCE_DIR}/randist/tdist.c
  ${GSL_SOURCE_DIR}/randist/weibull.c
  ${GSL_SOURCE_DIR}/randist/landau.c
  ${GSL_SOURCE_DIR}/dht/dht.c
  ${GSL_SOURCE_DIR}/ode-initval/control.c
  ${GSL_SOURCE_DIR}/ode-initval/cstd.c
  ${GSL_SOURCE_DIR}/ode-initval/evolve.c
  ${GSL_SOURCE_DIR}/ode-initval/step.c
  ${GSL_SOURCE_DIR}/ode-initval/rk2.c
  ${GSL_SOURCE_DIR}/ode-initval/rk2imp.c
  ${GSL_SOURCE_DIR}/ode-initval/rk4.c
  ${GSL_SOURCE_DIR}/ode-initval/rk4imp.c
  ${GSL_SOURCE_DIR}/ode-initval/rkf45.c
  ${GSL_SOURCE_DIR}/ode-initval/rk8pd.c
  ${GSL_SOURCE_DIR}/ode-initval/rkck.c
  ${GSL_SOURCE_DIR}/ode-initval/bsimp.c
  ${GSL_SOURCE_DIR}/ode-initval/gear1.c
  ${GSL_SOURCE_DIR}/ode-initval/gear2.c
  ${GSL_SOURCE_DIR}/permutation/init.c
  ${GSL_SOURCE_DIR}/permutation/file.c
  ${GSL_SOURCE_DIR}/permutation/permutation.c
  ${GSL_SOURCE_DIR}/permutation/permute.c
  ${GSL_SOURCE_DIR}/sum/levin_u.c
  ${GSL_SOURCE_DIR}/sum/levin_utrunc.c
  ${GSL_SOURCE_DIR}/sum/work_u.c
  ${GSL_SOURCE_DIR}/sum/work_utrunc.c
  ${GSL_SOURCE_DIR}/vector/init.c
  ${GSL_SOURCE_DIR}/vector/file.c
  ${GSL_SOURCE_DIR}/vector/vector.c
  ${GSL_SOURCE_DIR}/vector/copy.c
  ${GSL_SOURCE_DIR}/vector/swap.c
  ${GSL_SOURCE_DIR}/vector/prop.c
  ${GSL_SOURCE_DIR}/vector/minmax.c
  ${GSL_SOURCE_DIR}/vector/oper.c
  ${GSL_SOURCE_DIR}/vector/reim.c
  ${GSL_SOURCE_DIR}/vector/subvector.c
  ${GSL_SOURCE_DIR}/vector/view.c
  ${GSL_SOURCE_DIR}/vector/view.h
  ${GSL_SOURCE_DIR}/qrng/qrng.c
  ${GSL_SOURCE_DIR}/qrng/niederreiter-2.c
  ${GSL_SOURCE_DIR}/qrng/sobol.c
  ${GSL_SOURCE_DIR}/multifit/multilinear.c
  ${GSL_SOURCE_DIR}/multifit/work.c
  ${GSL_SOURCE_DIR}/multifit/lmder.c
  ${GSL_SOURCE_DIR}/multifit/fsolver.c
  ${GSL_SOURCE_DIR}/multifit/fdfsolver.c
  ${GSL_SOURCE_DIR}/multifit/convergence.c
  ${GSL_SOURCE_DIR}/multifit/gradient.c
  ${GSL_SOURCE_DIR}/multifit/covar.c
  ${GSL_SOURCE_DIR}/cblas/sasum.c
  ${GSL_SOURCE_DIR}/cblas/saxpy.c
  ${GSL_SOURCE_DIR}/cblas/scasum.c
  ${GSL_SOURCE_DIR}/cblas/scnrm2.c
  ${GSL_SOURCE_DIR}/cblas/scopy.c
  ${GSL_SOURCE_DIR}/cblas/sdot.c
  ${GSL_SOURCE_DIR}/cblas/sdsdot.c
  ${GSL_SOURCE_DIR}/cblas/sgbmv.c
  ${GSL_SOURCE_DIR}/cblas/sgemm.c
  ${GSL_SOURCE_DIR}/cblas/sgemv.c
  ${GSL_SOURCE_DIR}/cblas/sger.c
  ${GSL_SOURCE_DIR}/cblas/snrm2.c
  ${GSL_SOURCE_DIR}/cblas/srot.c
  ${GSL_SOURCE_DIR}/cblas/srotg.c
  ${GSL_SOURCE_DIR}/cblas/srotm.c
  ${GSL_SOURCE_DIR}/cblas/srotmg.c
  ${GSL_SOURCE_DIR}/cblas/ssbmv.c
  ${GSL_SOURCE_DIR}/cblas/sscal.c
  ${GSL_SOURCE_DIR}/cblas/sspmv.c
  ${GSL_SOURCE_DIR}/cblas/sspr.c
  ${GSL_SOURCE_DIR}/cblas/sspr2.c
  ${GSL_SOURCE_DIR}/cblas/sswap.c
  ${GSL_SOURCE_DIR}/cblas/ssymm.c
  ${GSL_SOURCE_DIR}/cblas/ssymv.c
  ${GSL_SOURCE_DIR}/cblas/ssyr.c
  ${GSL_SOURCE_DIR}/cblas/ssyr2.c
  ${GSL_SOURCE_DIR}/cblas/ssyr2k.c
  ${GSL_SOURCE_DIR}/cblas/ssyrk.c
  ${GSL_SOURCE_DIR}/cblas/stbmv.c
  ${GSL_SOURCE_DIR}/cblas/stbsv.c
  ${GSL_SOURCE_DIR}/cblas/stpmv.c
  ${GSL_SOURCE_DIR}/cblas/stpsv.c
  ${GSL_SOURCE_DIR}/cblas/strmm.c
  ${GSL_SOURCE_DIR}/cblas/strmv.c
  ${GSL_SOURCE_DIR}/cblas/strsm.c
  ${GSL_SOURCE_DIR}/cblas/strsv.c
  ${GSL_SOURCE_DIR}/cblas/dasum.c
  ${GSL_SOURCE_DIR}/cblas/daxpy.c
  ${GSL_SOURCE_DIR}/cblas/dcopy.c
  ${GSL_SOURCE_DIR}/cblas/ddot.c
  ${GSL_SOURCE_DIR}/cblas/dgbmv.c
  ${GSL_SOURCE_DIR}/cblas/dgemm.c
  ${GSL_SOURCE_DIR}/cblas/dgemv.c
  ${GSL_SOURCE_DIR}/cblas/dger.c
  ${GSL_SOURCE_DIR}/cblas/dnrm2.c
  ${GSL_SOURCE_DIR}/cblas/drot.c
  ${GSL_SOURCE_DIR}/cblas/drotg.c
  ${GSL_SOURCE_DIR}/cblas/drotm.c
  ${GSL_SOURCE_DIR}/cblas/drotmg.c
  ${GSL_SOURCE_DIR}/cblas/dsbmv.c
  ${GSL_SOURCE_DIR}/cblas/dscal.c
  ${GSL_SOURCE_DIR}/cblas/dsdot.c
  ${GSL_SOURCE_DIR}/cblas/dspmv.c
  ${GSL_SOURCE_DIR}/cblas/dspr.c
  ${GSL_SOURCE_DIR}/cblas/dspr2.c
  ${GSL_SOURCE_DIR}/cblas/dswap.c
  ${GSL_SOURCE_DIR}/cblas/dsymm.c
  ${GSL_SOURCE_DIR}/cblas/dsymv.c
  ${GSL_SOURCE_DIR}/cblas/dsyr.c
  ${GSL_SOURCE_DIR}/cblas/dsyr2.c
  ${GSL_SOURCE_DIR}/cblas/dsyr2k.c
  ${GSL_SOURCE_DIR}/cblas/dsyrk.c
  ${GSL_SOURCE_DIR}/cblas/dtbmv.c
  ${GSL_SOURCE_DIR}/cblas/dtbsv.c
  ${GSL_SOURCE_DIR}/cblas/dtpmv.c
  ${GSL_SOURCE_DIR}/cblas/dtpsv.c
  ${GSL_SOURCE_DIR}/cblas/dtrmm.c
  ${GSL_SOURCE_DIR}/cblas/dtrmv.c
  ${GSL_SOURCE_DIR}/cblas/dtrsm.c
  ${GSL_SOURCE_DIR}/cblas/dtrsv.c
  ${GSL_SOURCE_DIR}/cblas/dzasum.c
  ${GSL_SOURCE_DIR}/cblas/dznrm2.c
  ${GSL_SOURCE_DIR}/cblas/caxpy.c
  ${GSL_SOURCE_DIR}/cblas/ccopy.c
  ${GSL_SOURCE_DIR}/cblas/cdotc_sub.c
  ${GSL_SOURCE_DIR}/cblas/cdotu_sub.c
  ${GSL_SOURCE_DIR}/cblas/cgbmv.c
  ${GSL_SOURCE_DIR}/cblas/cgemm.c
  ${GSL_SOURCE_DIR}/cblas/cgemv.c
  ${GSL_SOURCE_DIR}/cblas/cgerc.c
  ${GSL_SOURCE_DIR}/cblas/cgeru.c
  ${GSL_SOURCE_DIR}/cblas/chbmv.c
  ${GSL_SOURCE_DIR}/cblas/chemm.c
  ${GSL_SOURCE_DIR}/cblas/chemv.c
  ${GSL_SOURCE_DIR}/cblas/cher.c
  ${GSL_SOURCE_DIR}/cblas/cher2.c
  ${GSL_SOURCE_DIR}/cblas/cher2k.c
  ${GSL_SOURCE_DIR}/cblas/cherk.c
  ${GSL_SOURCE_DIR}/cblas/chpmv.c
  ${GSL_SOURCE_DIR}/cblas/chpr.c
  ${GSL_SOURCE_DIR}/cblas/chpr2.c
  ${GSL_SOURCE_DIR}/cblas/cscal.c
  ${GSL_SOURCE_DIR}/cblas/csscal.c
  ${GSL_SOURCE_DIR}/cblas/cswap.c
  ${GSL_SOURCE_DIR}/cblas/csymm.c
  ${GSL_SOURCE_DIR}/cblas/csyr2k.c
  ${GSL_SOURCE_DIR}/cblas/csyrk.c
  ${GSL_SOURCE_DIR}/cblas/ctbmv.c
  ${GSL_SOURCE_DIR}/cblas/ctbsv.c
  ${GSL_SOURCE_DIR}/cblas/ctpmv.c
  ${GSL_SOURCE_DIR}/cblas/ctpsv.c
  ${GSL_SOURCE_DIR}/cblas/ctrmm.c
  ${GSL_SOURCE_DIR}/cblas/ctrmv.c
  ${GSL_SOURCE_DIR}/cblas/ctrsm.c
  ${GSL_SOURCE_DIR}/cblas/ctrsv.c
  ${GSL_SOURCE_DIR}/cblas/zaxpy.c
  ${GSL_SOURCE_DIR}/cblas/zcopy.c
  ${GSL_SOURCE_DIR}/cblas/zdotc_sub.c
  ${GSL_SOURCE_DIR}/cblas/zdotu_sub.c
  ${GSL_SOURCE_DIR}/cblas/zdscal.c
  ${GSL_SOURCE_DIR}/cblas/zgbmv.c
  ${GSL_SOURCE_DIR}/cblas/zgemm.c
  ${GSL_SOURCE_DIR}/cblas/zgemv.c
  ${GSL_SOURCE_DIR}/cblas/zgerc.c
  ${GSL_SOURCE_DIR}/cblas/zgeru.c
  ${GSL_SOURCE_DIR}/cblas/zhbmv.c
  ${GSL_SOURCE_DIR}/cblas/zhemm.c
  ${GSL_SOURCE_DIR}/cblas/zhemv.c
  ${GSL_SOURCE_DIR}/cblas/zher.c
  ${GSL_SOURCE_DIR}/cblas/zher2.c
  ${GSL_SOURCE_DIR}/cblas/zher2k.c
  ${GSL_SOURCE_DIR}/cblas/zherk.c
  ${GSL_SOURCE_DIR}/cblas/zhpmv.c
  ${GSL_SOURCE_DIR}/cblas/zhpr.c
  ${GSL_SOURCE_DIR}/cblas/zhpr2.c
  ${GSL_SOURCE_DIR}/cblas/zscal.c
  ${GSL_SOURCE_DIR}/cblas/zswap.c
  ${GSL_SOURCE_DIR}/cblas/zsymm.c
  ${GSL_SOURCE_DIR}/cblas/zsyr2k.c
  ${GSL_SOURCE_DIR}/cblas/zsyrk.c
  ${GSL_SOURCE_DIR}/cblas/ztbmv.c
  ${GSL_SOURCE_DIR}/cblas/ztbsv.c
  ${GSL_SOURCE_DIR}/cblas/ztpmv.c
  ${GSL_SOURCE_DIR}/cblas/ztpsv.c
  ${GSL_SOURCE_DIR}/cblas/ztrmm.c
  ${GSL_SOURCE_DIR}/cblas/ztrmv.c
  ${GSL_SOURCE_DIR}/cblas/ztrsm.c
  ${GSL_SOURCE_DIR}/cblas/ztrsv.c
  ${GSL_SOURCE_DIR}/cblas/icamax.c
  ${GSL_SOURCE_DIR}/cblas/idamax.c
  ${GSL_SOURCE_DIR}/cblas/isamax.c
  ${GSL_SOURCE_DIR}/cblas/izamax.c
  ${GSL_SOURCE_DIR}/cblas/xerbla.c
  ${GSL_SOURCE_DIR}/block/init.c
  ${GSL_SOURCE_DIR}/block/file.c
  ${GSL_SOURCE_DIR}/block/block.c
  ${GSL_SOURCE_DIR}/diff/diff.c
  ${GSL_SOURCE_DIR}/integration/qk15.c
  ${GSL_SOURCE_DIR}/integration/qk21.c
  ${GSL_SOURCE_DIR}/integration/qk31.c
  ${GSL_SOURCE_DIR}/integration/qk41.c
  ${GSL_SOURCE_DIR}/integration/qk51.c
  ${GSL_SOURCE_DIR}/integration/qk61.c
  ${GSL_SOURCE_DIR}/integration/qk.c
  ${GSL_SOURCE_DIR}/integration/qng.c
  ${GSL_SOURCE_DIR}/integration/qng.h
  ${GSL_SOURCE_DIR}/integration/qag.c
  ${GSL_SOURCE_DIR}/integration/qags.c
  ${GSL_SOURCE_DIR}/integration/qagp.c
  ${GSL_SOURCE_DIR}/integration/workspace.c
  ${GSL_SOURCE_DIR}/integration/qcheb.c
  ${GSL_SOURCE_DIR}/integration/qawc.c
  ${GSL_SOURCE_DIR}/integration/qmomo.c
  ${GSL_SOURCE_DIR}/integration/qaws.c
  ${GSL_SOURCE_DIR}/integration/qmomof.c
  ${GSL_SOURCE_DIR}/integration/qawo.c
  ${GSL_SOURCE_DIR}/integration/qawf.c
  ${GSL_SOURCE_DIR}/fit/linear.c
  ${GSL_SOURCE_DIR}/ieee-utils/print.c
  ${GSL_SOURCE_DIR}/ieee-utils/make_rep.c
  ${GSL_SOURCE_DIR}/ieee-utils/gsl_ieee_utils.h
  ${GSL_SOURCE_DIR}/ieee-utils/env.c
  ${GSL_SOURCE_DIR}/ieee-utils/fp.c
  ${GSL_SOURCE_DIR}/ieee-utils/read.c
  ${GSL_SOURCE_DIR}/eigen/jacobi.c
  ${GSL_SOURCE_DIR}/eigen/symm.c
  ${GSL_SOURCE_DIR}/eigen/symmv.c
  ${GSL_SOURCE_DIR}/eigen/herm.c
  ${GSL_SOURCE_DIR}/eigen/hermv.c
  ${GSL_SOURCE_DIR}/eigen/sort.c
  ${GSL_SOURCE_DIR}/statistics/mean.c
  ${GSL_SOURCE_DIR}/statistics/variance.c
  ${GSL_SOURCE_DIR}/statistics/absdev.c
  ${GSL_SOURCE_DIR}/statistics/skew.c
  ${GSL_SOURCE_DIR}/statistics/kurtosis.c
  ${GSL_SOURCE_DIR}/statistics/lag1.c
  ${GSL_SOURCE_DIR}/statistics/p_variance.c
  ${GSL_SOURCE_DIR}/statistics/minmax.c
  ${GSL_SOURCE_DIR}/statistics/ttest.c
  ${GSL_SOURCE_DIR}/statistics/median.c
  ${GSL_SOURCE_DIR}/statistics/covariance.c
  ${GSL_SOURCE_DIR}/statistics/quantiles.c
  ${GSL_SOURCE_DIR}/statistics/wmean.c
  ${GSL_SOURCE_DIR}/statistics/wvariance.c
  ${GSL_SOURCE_DIR}/statistics/wabsdev.c
  ${GSL_SOURCE_DIR}/statistics/wskew.c
  ${GSL_SOURCE_DIR}/statistics/wkurtosis.c
  ${GSL_SOURCE_DIR}/roots/bisection.c
  ${GSL_SOURCE_DIR}/roots/brent.c
  ${GSL_SOURCE_DIR}/roots/falsepos.c
  ${GSL_SOURCE_DIR}/roots/newton.c
  ${GSL_SOURCE_DIR}/roots/secant.c
  ${GSL_SOURCE_DIR}/roots/steffenson.c
  ${GSL_SOURCE_DIR}/roots/convergence.c
  ${GSL_SOURCE_DIR}/roots/fsolver.c
  ${GSL_SOURCE_DIR}/roots/fdfsolver.c
  ${GSL_SOURCE_DIR}/linalg/multiply.c
  ${GSL_SOURCE_DIR}/linalg/tridiag.c
  ${GSL_SOURCE_DIR}/linalg/tridiag.h
  ${GSL_SOURCE_DIR}/linalg/lu.c
  ${GSL_SOURCE_DIR}/linalg/luc.c
  ${GSL_SOURCE_DIR}/linalg/hh.c
  ${GSL_SOURCE_DIR}/linalg/qr.c
  ${GSL_SOURCE_DIR}/linalg/qrpt.c
  ${GSL_SOURCE_DIR}/linalg/svd.c
  ${GSL_SOURCE_DIR}/linalg/householder.c
  ${GSL_SOURCE_DIR}/linalg/householdercomplex.c
  ${GSL_SOURCE_DIR}/linalg/cholesky.c
  ${GSL_SOURCE_DIR}/linalg/symmtd.c
  ${GSL_SOURCE_DIR}/linalg/hermtd.c
  ${GSL_SOURCE_DIR}/linalg/bidiag.c
  ${GSL_SOURCE_DIR}/linalg/balance.c
  ${GSL_SOURCE_DIR}/min/fsolver.c
  ${GSL_SOURCE_DIR}/min/golden.c
  ${GSL_SOURCE_DIR}/min/brent.c
  ${GSL_SOURCE_DIR}/min/convergence.c
  ${GSL_SOURCE_DIR}/min/bracketing.c
  ${GSL_SOURCE_DIR}/utils/system.h
  ${GSL_SOURCE_DIR}/utils/placeholder.c
  ${GSL_SOURCE_DIR}/rng/rng.c
  ${GSL_SOURCE_DIR}/rng/types.c
  ${GSL_SOURCE_DIR}/rng/default.c
  ${GSL_SOURCE_DIR}/rng/cmrg.c
  ${GSL_SOURCE_DIR}/rng/gfsr4.c
  ${GSL_SOURCE_DIR}/rng/slatec.c
  ${GSL_SOURCE_DIR}/rng/minstd.c
  ${GSL_SOURCE_DIR}/rng/mrg.c
  ${GSL_SOURCE_DIR}/rng/mt.c
  ${GSL_SOURCE_DIR}/rng/r250.c
  ${GSL_SOURCE_DIR}/rng/ran0.c
  ${GSL_SOURCE_DIR}/rng/ran1.c
  ${GSL_SOURCE_DIR}/rng/ran2.c
  ${GSL_SOURCE_DIR}/rng/ran3.c
  ${GSL_SOURCE_DIR}/rng/rand.c
  ${GSL_SOURCE_DIR}/rng/random.c
  ${GSL_SOURCE_DIR}/rng/rand48.c
  ${GSL_SOURCE_DIR}/rng/randu.c
  ${GSL_SOURCE_DIR}/rng/ranf.c
  ${GSL_SOURCE_DIR}/rng/ranlux.c
  ${GSL_SOURCE_DIR}/rng/ranlxs.c
  ${GSL_SOURCE_DIR}/rng/ranlxd.c
  ${GSL_SOURCE_DIR}/rng/ranmar.c
  ${GSL_SOURCE_DIR}/rng/taus.c
  ${GSL_SOURCE_DIR}/rng/transputer.c
  ${GSL_SOURCE_DIR}/rng/tt.c
  ${GSL_SOURCE_DIR}/rng/uni.c
  ${GSL_SOURCE_DIR}/rng/uni32.c
  ${GSL_SOURCE_DIR}/rng/vax.c
  ${GSL_SOURCE_DIR}/rng/zuf.c
  ${GSL_SOURCE_DIR}/ntuple/ntuple.c
  ${GSL_SOURCE_DIR}/interpolation/accel.c
  ${GSL_SOURCE_DIR}/interpolation/akima.c
  ${GSL_SOURCE_DIR}/interpolation/bsearch.c
  ${GSL_SOURCE_DIR}/interpolation/cspline.c
  ${GSL_SOURCE_DIR}/interpolation/interp.c
  ${GSL_SOURCE_DIR}/interpolation/linear.c
  ${GSL_SOURCE_DIR}/interpolation/integ_eval.h
  ${GSL_SOURCE_DIR}/interpolation/spline.c
  ${GSL_SOURCE_DIR}/monte/miser.c
  ${GSL_SOURCE_DIR}/monte/plain.c
  ${GSL_SOURCE_DIR}/monte/gsl_monte_vegas.h
  ${GSL_SOURCE_DIR}/monte/gsl_monte_miser.h
  ${GSL_SOURCE_DIR}/monte/gsl_monte_plain.h
  ${GSL_SOURCE_DIR}/monte/gsl_monte.h
  ${GSL_SOURCE_DIR}/monte/vegas.c
  ${GSL_SOURCE_DIR}/poly/eval.c
  ${GSL_SOURCE_DIR}/poly/solve_quadratic.c
  ${GSL_SOURCE_DIR}/poly/solve_cubic.c
  ${GSL_SOURCE_DIR}/poly/zsolve_quadratic.c
  ${GSL_SOURCE_DIR}/poly/zsolve_cubic.c
  ${GSL_SOURCE_DIR}/poly/zsolve.c
  ${GSL_SOURCE_DIR}/poly/zsolve_init.c
  ${GSL_SOURCE_DIR}/blas/blas.c
  ${GSL_SOURCE_DIR}/err/error.c
  ${GSL_SOURCE_DIR}/err/stream.c
  ${GSL_SOURCE_DIR}/err/message.c
  ${GSL_SOURCE_DIR}/err/strerror.c
  ${GSL_SOURCE_DIR}/err/warn.c
  ${GSL_SOURCE_DIR}/cheb/deriv.c
  ${GSL_SOURCE_DIR}/cheb/eval.c
  ${GSL_SOURCE_DIR}/cheb/init.c
  ${GSL_SOURCE_DIR}/cheb/integ.c
  ${GSL_SOURCE_DIR}/siman/siman.c
  ${GSL_SOURCE_DIR}/complex/math.c
  ${GSL_SOURCE_DIR}/matrix/init.c
  ${GSL_SOURCE_DIR}/matrix/matrix.c
  ${GSL_SOURCE_DIR}/matrix/file.c
  ${GSL_SOURCE_DIR}/matrix/rowcol.c
  ${GSL_SOURCE_DIR}/matrix/swap.c
  ${GSL_SOURCE_DIR}/matrix/copy.c
  ${GSL_SOURCE_DIR}/matrix/minmax.c
  ${GSL_SOURCE_DIR}/matrix/prop.c
  ${GSL_SOURCE_DIR}/matrix/oper.c
  ${GSL_SOURCE_DIR}/matrix/getset.c
  ${GSL_SOURCE_DIR}/matrix/view.c
  ${GSL_SOURCE_DIR}/matrix/submatrix.c
  ${GSL_SOURCE_DIR}/matrix/view.h
  ${GSL_SOURCE_DIR}/fft/dft.c
  ${GSL_SOURCE_DIR}/fft/fft.c
  ${GSL_SOURCE_DIR}/sort/sort.c
  ${GSL_SOURCE_DIR}/sort/sortind.c
  ${GSL_SOURCE_DIR}/sort/sortvec.c
  ${GSL_SOURCE_DIR}/sort/sortvecind.c
  ${GSL_SOURCE_DIR}/sort/subset.c
  ${GSL_SOURCE_DIR}/sort/subsetind.c
  ${GSL_SOURCE_DIR}/sys/minmax.c
  ${GSL_SOURCE_DIR}/sys/prec.c
  ${GSL_SOURCE_DIR}/sys/hypot.c
  ${GSL_SOURCE_DIR}/sys/log1p.c
  ${GSL_SOURCE_DIR}/sys/expm1.c
  ${GSL_SOURCE_DIR}/sys/coerce.c
  ${GSL_SOURCE_DIR}/sys/invhyp.c
  ${GSL_SOURCE_DIR}/sys/pow_int.c
  ${GSL_SOURCE_DIR}/sys/infnan.c
  ${GSL_SOURCE_DIR}/sys/fdiv.c
  ${GSL_SOURCE_DIR}/specfunc/airy.c
  ${GSL_SOURCE_DIR}/specfunc/airy_der.c
  ${GSL_SOURCE_DIR}/specfunc/airy_zero.c
  ${GSL_SOURCE_DIR}/specfunc/atanint.c
  ${GSL_SOURCE_DIR}/specfunc/bessel.c
  ${GSL_SOURCE_DIR}/specfunc/bessel.h
  ${GSL_SOURCE_DIR}/specfunc/bessel_I0.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_I1.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_In.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_Inu.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_J0.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_J1.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_Jn.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_Jnu.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_K0.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_K1.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_Kn.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_Knu.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_Y0.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_Y1.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_Yn.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_Ynu.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_amp_phase.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_amp_phase.h
  ${GSL_SOURCE_DIR}/specfunc/bessel_i.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_j.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_k.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_olver.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_temme.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_y.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_zero.c
  ${GSL_SOURCE_DIR}/specfunc/bessel_sequence.c
  ${GSL_SOURCE_DIR}/specfunc/beta.c
  ${GSL_SOURCE_DIR}/specfunc/beta_inc.c
  ${GSL_SOURCE_DIR}/specfunc/clausen.c
  ${GSL_SOURCE_DIR}/specfunc/coulomb.c
  ${GSL_SOURCE_DIR}/specfunc/coupling.c
  ${GSL_SOURCE_DIR}/specfunc/coulomb_bound.c
  ${GSL_SOURCE_DIR}/specfunc/dawson.c
  ${GSL_SOURCE_DIR}/specfunc/debye.c
  ${GSL_SOURCE_DIR}/specfunc/dilog.c
  ${GSL_SOURCE_DIR}/specfunc/elementary.c
  ${GSL_SOURCE_DIR}/specfunc/ellint.c
  ${GSL_SOURCE_DIR}/specfunc/elljac.c
  ${GSL_SOURCE_DIR}/specfunc/erfc.c
  ${GSL_SOURCE_DIR}/specfunc/exp.c
  ${GSL_SOURCE_DIR}/specfunc/expint.c
  ${GSL_SOURCE_DIR}/specfunc/expint3.c
  ${GSL_SOURCE_DIR}/specfunc/fermi_dirac.c
  ${GSL_SOURCE_DIR}/specfunc/gegenbauer.c
  ${GSL_SOURCE_DIR}/specfunc/gamma.c
  ${GSL_SOURCE_DIR}/specfunc/gamma_inc.c
  ${GSL_SOURCE_DIR}/specfunc/hyperg_0F1.c
  ${GSL_SOURCE_DIR}/specfunc/hyperg_2F0.c
  ${GSL_SOURCE_DIR}/specfunc/hyperg_1F1.c
  ${GSL_SOURCE_DIR}/specfunc/hyperg_2F1.c
  ${GSL_SOURCE_DIR}/specfunc/hyperg_U.c
  ${GSL_SOURCE_DIR}/specfunc/hyperg.c
  ${GSL_SOURCE_DIR}/specfunc/laguerre.c
  ${GSL_SOURCE_DIR}/specfunc/lambert.c
  ${GSL_SOURCE_DIR}/specfunc/legendre_H3d.c
  ${GSL_SOURCE_DIR}/specfunc/legendre_Qn.c
  ${GSL_SOURCE_DIR}/specfunc/legendre_con.c
  ${GSL_SOURCE_DIR}/specfunc/legendre_poly.c
  ${GSL_SOURCE_DIR}/specfunc/log.c
  ${GSL_SOURCE_DIR}/specfunc/poch.c
  ${GSL_SOURCE_DIR}/specfunc/pow_int.c
  ${GSL_SOURCE_DIR}/specfunc/psi.c
  ${GSL_SOURCE_DIR}/specfunc/recurse.h
  ${GSL_SOURCE_DIR}/specfunc/result.c
  ${GSL_SOURCE_DIR}/specfunc/shint.c
  ${GSL_SOURCE_DIR}/specfunc/sinint.c
  ${GSL_SOURCE_DIR}/specfunc/synchrotron.c
  ${GSL_SOURCE_DIR}/specfunc/transport.c
  ${GSL_SOURCE_DIR}/specfunc/trig.c
  ${GSL_SOURCE_DIR}/specfunc/zeta.c
  ${GSL_SOURCE_DIR}/multimin/fdfminimizer.c
  ${GSL_SOURCE_DIR}/multimin/steepest_descent.c
  ${GSL_SOURCE_DIR}/multimin/conjugate_fr.c
  ${GSL_SOURCE_DIR}/multimin/conjugate_pr.c
  ${GSL_SOURCE_DIR}/multimin/convergence.c
  ${GSL_SOURCE_DIR}/multimin/diff.c
  ${GSL_SOURCE_DIR}/multimin/vector_bfgs.c
  ${GSL_SOURCE_DIR}/histogram/add.c
  ${GSL_SOURCE_DIR}/histogram/get.c
  ${GSL_SOURCE_DIR}/histogram/init.c
  ${GSL_SOURCE_DIR}/histogram/params.c
  ${GSL_SOURCE_DIR}/histogram/reset.c
  ${GSL_SOURCE_DIR}/histogram/file.c
  ${GSL_SOURCE_DIR}/histogram/pdf.c
  ${GSL_SOURCE_DIR}/histogram/gsl_histogram.h
  ${GSL_SOURCE_DIR}/histogram/add2d.c
  ${GSL_SOURCE_DIR}/histogram/get2d.c
  ${GSL_SOURCE_DIR}/histogram/init2d.c
  ${GSL_SOURCE_DIR}/histogram/params2d.c
  ${GSL_SOURCE_DIR}/histogram/reset2d.c
  ${GSL_SOURCE_DIR}/histogram/file2d.c
  ${GSL_SOURCE_DIR}/histogram/pdf2d.c
  ${GSL_SOURCE_DIR}/histogram/gsl_histogram2d.h
  ${GSL_SOURCE_DIR}/histogram/calloc_range.c
  ${GSL_SOURCE_DIR}/histogram/calloc_range2d.c
  ${GSL_SOURCE_DIR}/histogram/copy.c
  ${GSL_SOURCE_DIR}/histogram/copy2d.c
  ${GSL_SOURCE_DIR}/histogram/maxval.c
  ${GSL_SOURCE_DIR}/histogram/maxval2d.c
  ${GSL_SOURCE_DIR}/histogram/oper.c
  ${GSL_SOURCE_DIR}/histogram/oper2d.c
  ${GSL_SOURCE_DIR}/histogram/stat.c
  ${GSL_SOURCE_DIR}/test/results.c
  ${GSL_SOURCE_DIR}/multiroots/fdjac.c
  ${GSL_SOURCE_DIR}/multiroots/fsolver.c
  ${GSL_SOURCE_DIR}/multiroots/fdfsolver.c
  ${GSL_SOURCE_DIR}/multiroots/convergence.c
  ${GSL_SOURCE_DIR}/multiroots/newton.c
  ${GSL_SOURCE_DIR}/multiroots/gnewton.c
  ${GSL_SOURCE_DIR}/multiroots/dnewton.c
  ${GSL_SOURCE_DIR}/multiroots/broyden.c
  ${GSL_SOURCE_DIR}/multiroots/hybrid.c
  ${GSL_SOURCE_DIR}/multiroots/hybridj.c
  ${GSL_SOURCE_DIR}/randist/bernoulli.c
  ${GSL_SOURCE_DIR}/randist/beta.c
  ${GSL_SOURCE_DIR}/randist/bigauss.c
  ${GSL_SOURCE_DIR}/randist/binomial.c
  ${GSL_SOURCE_DIR}/randist/cauchy.c
  ${GSL_SOURCE_DIR}/randist/chisq.c
  ${GSL_SOURCE_DIR}/randist/discrete.c
  ${GSL_SOURCE_DIR}/randist/erlang.c
  ${GSL_SOURCE_DIR}/randist/exponential.c
  ${GSL_SOURCE_DIR}/randist/exppow.c
  ${GSL_SOURCE_DIR}/randist/fdist.c
  ${GSL_SOURCE_DIR}/randist/flat.c
  ${GSL_SOURCE_DIR}/randist/gamma.c
  ${GSL_SOURCE_DIR}/randist/gauss.c
  ${GSL_SOURCE_DIR}/randist/gausstail.c
  ${GSL_SOURCE_DIR}/randist/geometric.c
  ${GSL_SOURCE_DIR}/randist/gumbel.c
  ${GSL_SOURCE_DIR}/randist/hyperg.c
  ${GSL_SOURCE_DIR}/randist/laplace.c
  ${GSL_SOURCE_DIR}/randist/levy.c
  ${GSL_SOURCE_DIR}/randist/logarithmic.c
  ${GSL_SOURCE_DIR}/randist/logistic.c
  ${GSL_SOURCE_DIR}/randist/lognormal.c
  ${GSL_SOURCE_DIR}/randist/nbinomial.c
  ${GSL_SOURCE_DIR}/randist/pareto.c
  ${GSL_SOURCE_DIR}/randist/pascal.c
  ${GSL_SOURCE_DIR}/randist/poisson.c
  ${GSL_SOURCE_DIR}/randist/rayleigh.c
  ${GSL_SOURCE_DIR}/randist/shuffle.c
  ${GSL_SOURCE_DIR}/randist/sphere.c
  ${GSL_SOURCE_DIR}/randist/tdist.c
  ${GSL_SOURCE_DIR}/randist/weibull.c
  ${GSL_SOURCE_DIR}/randist/landau.c
)
